// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8GEa0eVaNdBNMn0a_0RKcNOClxNZNew',
    appId: '1:812838073931:web:b22e530d27f2434af97fce',
    messagingSenderId: '812838073931',
    projectId: 'qr-code-57b9c',
    authDomain: 'qr-code-57b9c.firebaseapp.com',
    storageBucket: 'qr-code-57b9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYof_zZW_Ae6qnITkfEZvkPLRkkwFbslU',
    appId: '1:812838073931:android:363086fcfac691c5f97fce',
    messagingSenderId: '812838073931',
    projectId: 'qr-code-57b9c',
    storageBucket: 'qr-code-57b9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxE2wPOQmEFmN4Lvdd-k8jQFwsjW_WFw',
    appId: '1:812838073931:ios:9af25d357e4abbcbf97fce',
    messagingSenderId: '812838073931',
    projectId: 'qr-code-57b9c',
    storageBucket: 'qr-code-57b9c.appspot.com',
    iosClientId: '812838073931-u8986n35tl74tci8u9mgea18o3baoaek.apps.googleusercontent.com',
    iosBundleId: 'com.waprabowoo.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxE2wPOQmEFmN4Lvdd-k8jQFwsjW_WFw',
    appId: '1:812838073931:ios:9af25d357e4abbcbf97fce',
    messagingSenderId: '812838073931',
    projectId: 'qr-code-57b9c',
    storageBucket: 'qr-code-57b9c.appspot.com',
    iosClientId: '812838073931-u8986n35tl74tci8u9mgea18o3baoaek.apps.googleusercontent.com',
    iosBundleId: 'com.waprabowoo.qrCode',
  );
}
